// Code generated by goctl. DO NOT EDIT.
package types

type SendVerificationCodeReq struct {
	Phone string `json:"phone" validate:"required,phone"`
}

type SendVerificationCodeResp struct {
	VerificationCode string `json:"verification_code"`
}

type RegisterOrLoginByPhoneReq struct {
	Phone            string `json:"phone" validate:"required,phone"`
	VerificationCode string `json:"verification_code"  validate:"required,max=6,min=6"`
}

type RegisterOrLoginResp struct {
	UserId       int64  `json:"user_id"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type RegisterOrLoginByPasswordReq struct {
	Phone    string `json:"phone" validate:"required"`                 // 手机号
	Password string `json:"password" validate:"required,max=32,min=6"` // 用户密码，MD5加密
}

type ResetPassword struct {
	UserId      int64  `json:"user_id"` // 用户id
	NewPassword string `json:"new_password" validate:"required,max=32,min=6"`
}

type UserInfoReq struct {
	UserId int64 `form:"user_id"` // 用户id
}

type UserInfoResp struct {
	UserInfo *UserInfoItem `json:"userinfo"`
}

type UserInfoItem struct {
	ID              int64  `json:"id"`
	Phone           string `json:"phone"`
	NickName        string `json:"nickname"`
	IsFollow        bool   `json:"is_follow"`
	Avatar          string `json:"avatar"`
	BackgroundImage string `json:"background_image"`
	Signature       string `json:"signature"`
	TotalFavorited  int64  `json:"total_favorited"`
	WorkCount       int64  `json:"work_count"`
	FavoriteCount   int64  `json:"favorite_count"`
	FollowCount     int64  `json:"follow_count"`
	FollowerCount   int64  `json:"follower_count"`
}

type TokenResp struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

type ModifyUserInfoReq struct {
	Types int64  `json:"types" validate:"gte=1,lte=4"`
	Value string `json:"value"`
}
