// Code generated by goctl. DO NOT EDIT.
// Source: video.proto

package server

import (
	"context"

	"douniu/server/video/internal/logic"
	"douniu/server/video/internal/svc"
	"douniu/server/video/pb"
)

type VideoRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVideoRpcServer
}

func NewVideoRpcServer(svcCtx *svc.ServiceContext) *VideoRpcServer {
	return &VideoRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoRpcServer) GetAuthorId(ctx context.Context, in *pb.GetAuthorIdReq) (*pb.GetAuthorIdResp, error) {
	l := logic.NewGetAuthorIdLogic(ctx, s.svcCtx)
	return l.GetAuthorId(in)
}
