// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"douniu/server/video/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/upload/video",
				Handler: UploadVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/upload/cover",
				Handler: UploadCoverHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/publish",
				Handler: PublishVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/userlist",
				Handler: UserVideoListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/feed",
				Handler: VideoListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JWTAuth.AccessSecret),
		rest.WithPrefix("/douniu/video"),
		rest.WithTimeout(9999999000*time.Millisecond),
	)
}
