// Code generated by goctl. DO NOT EDIT.
package types

type AuthorInfo struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	FollowCount     int64  `json:"follow_count"`
	FollowerCount   int64  `json:"follower_count"`
	IsFollow        bool   `json:"is_follow"`
	Avatar          string `json:"avatar"`
	BackgroundImage string `json:"background_image"`
	Signature       string `json:"signature"`
	TotalFavorited  string `json:"total_favorited"`
	WorkCount       int64  `json:"work_count"`
	FavoriteCount   int64  `json:"favorite_count"`
}

type VideoInfo struct {
	ID            int64      `json:"id"`
	Author        AuthorInfo `json:"author"`
	PlayURL       string     `json:"play_url"`
	CoverURL      string     `json:"cover_url"`
	FavoriteCount int64      `json:"favorite_count"`
	CommentCount  int64      `json:"comment_count"`
	IsFavorite    bool       `json:"is_favorite"`
	Title         string     `json:"title"`
	Partition     int64      `json:"partition"`
	CreateTime    string     `json:"create_time"`
}

type VideoList struct {
	List []*VideoInfo `json:"video_list"`
}

type UploadVideoReq struct {
}

type UploadVideoResp struct {
	VideoId             int64  `json:"video_id"`
	VideoUrl            string `json:"video_url"`
	RecommendCoverUrl_1 string `json:"recommend_cover_url_1"`
	RecommendCoverUrl_2 string `json:"recommend_cover_url_2"`
	RecommendCoverUrl_3 string `json:"recommend_cover_url_3"`
}

type UploadCoverReq struct {
}

type UploadCoverResp struct {
	CoverUrl string `json:"cover_url"`
}

type PublishVideoReq struct {
	VideoId   int64  `json:"video_id"`
	VideoUrl  string `json:"video_url"`
	CoverUrl  string `json:"cover_url"`
	Title     string `json:"title"`
	Partition int64  `json:"partition"`
}

type UserVideoListReq struct {
	UserId string `form:"user_id"`
}

type UserVideoListResp struct {
	VideoList
}

type VideoListReq struct {
	LatestTime string `form:"latest_time,optional"`
}

type VideoListResp struct {
	NextTime int64 `json:"next_time"`
	VideoList
}
