// Code generated by goctl. DO NOT EDIT.
package types

type FavoriteLikeRequest struct {
	VideoId    int64 `json:"video_id"`
	ActionType int64 `json:"action_type"`
}

type FavoriteLikeResponse struct {
}
