name: Docker Build and Push Favorite
on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'go'
        required: true
#on:
#  push:
#    branches:
#      - dev
jobs:
  # favorite-api
  build-and-push-favorite-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push favorite-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/favorite/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}favorite-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/douniu
            docker-compose stop favorite-api
            docker-compose rm -f favorite-api
            docker image rm ${{ secrets.DOCKERHUB_IMAGE }}favorite-api:latest
            docker-compose -f docker-compose.yaml up -d favorite-api


  # favorite-rpc
  build-and-push-favorite-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push favorite-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/favorite/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}favorite-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/douniu
            docker-compose stop favorite-rpc
            docker-compose rm -f favorite-rpc
            docker image rm ${{ secrets.DOCKERHUB_IMAGE }}favorite-rpc:latest
            docker-compose -f docker-compose.yaml up -d favorite-rpc
  # favorite-mq
  build-and-push-favorite-mq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push favorite-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/favorite/mq/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}favorite-mq:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/douniu
            docker-compose stop favorite-mq
            docker-compose rm -f favorite-mq
            docker image rm ${{ secrets.DOCKERHUB_IMAGE }}favorite-mq:latest
            docker-compose -f docker-compose.yaml up -d favorite-mq