name: Docker Build and Push Relation
on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'go'
        required: true
jobs:

  # relation-rpc
  build-and-push-relation-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push relation-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/relation/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}relation-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/douniu
            docker-compose.yaml stop relation-rpc
            docker-compose.yaml rm -f relation-rpc
            docker image rm ${{ secrets.DOCKERHUB_IMAGE }}relation-rpc:latest
            docker-compose -f docker-compose.yaml up -d relation-rpc
  # relation-api
  build-and-push-relation-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push relation-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/relation/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}relation-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/douniu
            docker-compose.yaml stop relation-api
            docker-compose.yaml rm -f relation-api
            docker image rm ${{ secrets.DOCKERHUB_IMAGE }}relation-api:latest
            docker-compose -f docker-compose.yaml up -d relation-api
