name: Docker Build and Push User
on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'go'
        required: true
#on:
#  push:
#    branches:
#      - dev
jobs:
  # user-api
  build-and-push-user-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push user-api Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/user/api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}user-api:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/douniu
            docker-compose stop user-api
            docker-compose rm -f user-api
            docker image rm ${{ secrets.DOCKERHUB_IMAGE }}user-api:latest
            docker-compose -f docker-compose.yaml up -d user-api

  # user-rpc
  build-and-push-user-rpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create and push user-rpc Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/user/rpc/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE }}user-rpc:latest
          platforms: linux/amd64,linux/arm64  # 构建多个架构的镜像
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/douniu
            docker-compose stop user-rpc
            docker-compose rm -f user-rpc
            docker image rm ${{ secrets.DOCKERHUB_IMAGE }}user-rpc:latest
            docker-compose -f docker-compose.yaml up -d user-rpc